name: 'xcresult'
description: 'Generates annotations from an xcresult bundle'
author: 'Nomasystems'
inputs:
  xcresult-path:
    description: 'Path to the xcresult bundle'
    required: true
  path-root:
    description: 'Root for paths in the xcresult bundle. Defaults to env.GITHUB_WORKSPACE'
  fail-on-error:
    description: 'Set a failure exit code if the xcresult indicates an error'
    default: true
  fail-on-warning:
    description: 'Set a failure exit code if the xcresult indicates a warning'
    default: true
  fail-on-external-warning:
    description: 'Whether fail-on-warning considers warnings in files outside path-root'
    default: false
  fail-on-analyzer-warning:
    description: 'Set a failure exit code if the xcresult indicates an analyzer warning'
    default: true
  fail-on-test-failure:
    description: 'Set a failure exit code if the xcresult indicates a test failure'
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
