/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * xcresult-to-json output
 */
export interface Output {
  metrics?: Metrics;
  annotations: Annotation[];
  [k: string]: unknown;
}
export interface Metrics {
  analyzerWarningCount: number;
  errorCount: number;
  externalWarningCount: number;
  testCount: number;
  testFailedCount: number;
  testSkippedCount: number;
  warningCount: number;
  [k: string]: unknown;
}
export interface Annotation {
  /**
   * The file path
   */
  path?: string;
  /**
   * Whether path is relative
   */
  isPathRelative: boolean;
  location?: SourceLocation;
  /**
   * The level of the annotation.
   */
  annotationLevel: "notice" | "warning" | "failure";
  /**
   * A short description
   */
  message: string;
  /**
   * Title
   */
  title: string;
  [k: string]: unknown;
}
export interface SourceLocation {
  startLine: number;
  endLine: number;
  startColumn?: number;
  endColumn?: number;
  [k: string]: unknown;
}
